//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brokers
    {
        public int B_Code { get; set; }
        public string B_ShortCut1 { get; set; }
        public string B_ShortCut2 { get; set; }
        public string B_Name1 { get; set; }
        public string B_Name2 { get; set; }
        public string B_Address { get; set; }
        public string B_Zip { get; set; }
        public string B_Area { get; set; }
        public string B_Tel { get; set; }
        public string B_Fax { get; set; }
        public string B_Telex { get; set; }
        public string B_Number { get; set; }
        public Nullable<short> B_Class { get; set; }
        public string B_Account { get; set; }
        public Nullable<short> B_Blocked { get; set; }
        public string B_Comment { get; set; }
        public string B_LinkExport1 { get; set; }
        public string B_LinkExport2 { get; set; }
        public Nullable<short> B_Active { get; set; }
        public short B_BlockBroker { get; set; }
        public string B_SatCode { get; set; }
        public string B_ComAcount { get; set; }
        public Nullable<int> B_ComCurr { get; set; }
        public Nullable<int> B_Country { get; set; }
        public Nullable<short> B_Location { get; set; }
        public Nullable<short> B_Type { get; set; }
        public string B_SwiftAddress { get; set; }
        public string B_EconomyDivisionCode { get; set; }
        public string B_AFM { get; set; }
        public string B_CodeToNationalBank { get; set; }
        public string B_BalanceCode { get; set; }
        public short B_AcceptIncSwiftInstr { get; set; }
        public string B_ARMAE { get; set; }
        public double B_OwnCapital { get; set; }
        public Nullable<int> B_OwnCapitalCcy { get; set; }
        public string B_Auditor { get; set; }
        public Nullable<int> B_LngTermRating { get; set; }
        public Nullable<int> B_ShrtTermRating { get; set; }
        public Nullable<int> B_AltLngTermRating { get; set; }
        public Nullable<int> B_AltShrtTermRating { get; set; }
        public short B_HasCreditRisk { get; set; }
        public Nullable<int> B_OwnerGroup { get; set; }
        public Nullable<int> B_BRGGroupCode { get; set; }
        public int B_CMApproved { get; set; }
        public int B_MMApproved { get; set; }
        public string B_BicCode { get; set; }
        public Nullable<int> B_Rating { get; set; }
        public Nullable<int> B_AltRating { get; set; }
        public string B_ReutersCode { get; set; }
        public string B_BloombergCode { get; set; }
        public int B_PledgeBrcode { get; set; }
        public Nullable<int> B_CustodyFeeGroupId { get; set; }
        public Nullable<byte> B_AMLControl { get; set; }
        public byte B_ATSComType { get; set; }
        public Nullable<int> B_ReconGroupCode { get; set; }
        public Nullable<short> B_ReconSumSign { get; set; }
        public byte B_PfolioCodeRequired { get; set; }
        public byte B_OrderTransBehavior { get; set; }
        public bool B_AllowBulkOrders { get; set; }
        public bool B_IncludeInCMAR { get; set; }
        public bool B_IncludeInTRS { get; set; }
        public Nullable<int> B_BrokerFeesPlanID { get; set; }
    }
}
