//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int CRY_Code { get; set; }
        public string CRY_Shortcut { get; set; }
        public string CRY_Name { get; set; }
        public string CRY_Name1 { get; set; }
        public string CRY_Name2 { get; set; }
        public short CRY_LOCATION { get; set; }
        public int CRY_IslamWKD { get; set; }
        public Nullable<int> CRY_MCID { get; set; }
        public Nullable<int> CRY_RGID { get; set; }
        public string CRY_CodeEx { get; set; }
        public bool CRY_CRSReportable { get; set; }
        public Nullable<System.DateTime> CRY_CRSEffectiveDate { get; set; }
    
        public virtual MarketCategory MarketCategory { get; set; }
        public virtual Region Region { get; set; }
    }
}
