//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFeedModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalFeedModels()
        {
            this.Currencies = new HashSet<Currencies>();
        }
    
        public int EFM_ID { get; set; }
        public Nullable<int> EFM_RTFeedProviderId { get; set; }
        public Nullable<int> EFM_AutoUpdStaticProviderId { get; set; }
        public Nullable<int> EFM_AutoFeedPriceProviderId { get; set; }
        public Nullable<int> EFM_ExPrFeedModelID { get; set; }
        public string EFM_Description1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies { get; set; }
    }
}
