//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Portfolios()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int PF_Code { get; set; }
        public string PF_ShortCut1 { get; set; }
        public string PF_ShortCut2 { get; set; }
        public Nullable<int> PF_PCenter { get; set; }
        public Nullable<short> PF_Branch { get; set; }
        public string PF_SName1 { get; set; }
        public string PF_SName2 { get; set; }
        public string PF_FName1 { get; set; }
        public string PF_FName2 { get; set; }
        public string PF_PName1 { get; set; }
        public string PF_PName2 { get; set; }
        public string PF_EMail { get; set; }
        public Nullable<int> PF_InstInv { get; set; }
        public Nullable<short> PF_Model { get; set; }
        public string PF_Address { get; set; }
        public string PF_Area { get; set; }
        public string PF_Town { get; set; }
        public string PF_Zip { get; set; }
        public string PF_Fax { get; set; }
        public string PF_Telex { get; set; }
        public Nullable<short> PF_SendFax { get; set; }
        public Nullable<System.DateTime> PF_InitDate { get; set; }
        public Nullable<System.DateTime> PF_FInvDate { get; set; }
        public Nullable<double> PF_InitCash { get; set; }
        public Nullable<float> PF_CashBase { get; set; }
        public Nullable<int> PF_Currency { get; set; }
        public string PF_Account1 { get; set; }
        public string PF_Account2 { get; set; }
        public string PF_Account3 { get; set; }
        public string PF_Comment { get; set; }
        public Nullable<int> PF_Report { get; set; }
        public Nullable<short> PF_ReportType { get; set; }
        public Nullable<short> PF_RPeriod { get; set; }
        public Nullable<System.DateTime> PF_NextDate { get; set; }
        public Nullable<short> PF_CharSet { get; set; }
        public Nullable<short> PF_ReportLanguage { get; set; }
        public Nullable<short> PF_ObjectSet { get; set; }
        public Nullable<short> PF_EvalBond { get; set; }
        public Nullable<short> PF_Evaluate { get; set; }
        public Nullable<short> PF_Evaluate2 { get; set; }
        public string PF_Field1 { get; set; }
        public string PF_Field2 { get; set; }
        public string PF_Field3 { get; set; }
        public string PF_Field4 { get; set; }
        public string PF_Field5 { get; set; }
        public string PF_Field6 { get; set; }
        public Nullable<bool> PF_Active { get; set; }
        public string PF_LinkInput1 { get; set; }
        public string PF_LinkInput2 { get; set; }
        public string PF_LinkInput3 { get; set; }
        public string PF_LinkInput4 { get; set; }
        public string PF_LinkInput5 { get; set; }
        public string PF_LinkExport1 { get; set; }
        public string PF_LinkExport2 { get; set; }
        public string PF_IDCardNo { get; set; }
        public string PF_AFM { get; set; }
        public string PF_DOY { get; set; }
        public string PF_Activity { get; set; }
        public Nullable<System.DateTime> PF_CExpDate { get; set; }
        public string PF_SATCode { get; set; }
        public string PF_SATAccount { get; set; }
        public Nullable<int> PF_PGROUP { get; set; }
        public Nullable<int> PF_ADDCRY { get; set; }
        public short PF_SENDMETHOD { get; set; }
        public Nullable<short> PF_SEASTATUS { get; set; }
        public Nullable<short> PF_SENDREP { get; set; }
        public Nullable<int> PF_SENDADDRID { get; set; }
        public int PF_InvCateg { get; set; }
        public Nullable<short> PF_READY_STAT { get; set; }
        public Nullable<System.DateTime> PF_BIRTHDATE { get; set; }
        public Nullable<int> PF_IDTYPE { get; set; }
        public string PF_IDNUMBER { get; set; }
        public string PF_IDissuer { get; set; }
        public Nullable<int> PF_IDcountry { get; set; }
        public Nullable<System.DateTime> PF_IDDATEISSUE { get; set; }
        public Nullable<System.DateTime> PF_DeactiveDate { get; set; }
        public Nullable<int> PF_Resident { get; set; }
        public Nullable<int> PF_Citizenship { get; set; }
        public short PF_AXETransferStatus { get; set; }
        public short PF_SATEXPORT { get; set; }
        public short PF_CashPFolio { get; set; }
        public int PF_CPFCode { get; set; }
        public string PF_CRS { get; set; }
        public Nullable<short> PF_CustService { get; set; }
        public short PF_IsInvAccount { get; set; }
        public int pf_ApproveIn { get; set; }
        public Nullable<short> PF_AOId { get; set; }
        public string PF_InvHorizon { get; set; }
        public int PF_InvRangeMin { get; set; }
        public int PF_InvRangeMax { get; set; }
        public int PF_InvRisk { get; set; }
        public string PF_InvRefPfolio { get; set; }
        public string PF_InvRefIndex { get; set; }
        public Nullable<int> PF_InvRefBenchmark { get; set; }
        public Nullable<int> PF_DefTRBroker { get; set; }
        public Nullable<int> PF_DefCSBroker { get; set; }
        public Nullable<int> PF_DefTSBroker { get; set; }
        public short PF_BOGExclude { get; set; }
        public int PF_ManageType { get; set; }
        public short PF_AXEExport { get; set; }
        public int PF_DocPerTrade { get; set; }
        public Nullable<int> PF_BenchPFolio { get; set; }
        public string PF_Tel { get; set; }
        public byte PF_ISKEM { get; set; }
        public string PF_Call1 { get; set; }
        public string PF_Call2 { get; set; }
        public bool PF_IsStaff { get; set; }
        public bool PF_IsMargin { get; set; }
        public Nullable<int> PF_PriceProvider { get; set; }
        public Nullable<int> PF_tsamgId { get; set; }
        public bool PF_Amortization { get; set; }
        public string PF_SATCode2 { get; set; }
        public string PF_SATAccount2 { get; set; }
        public string PF_Prefix { get; set; }
        public bool PF_HasContractFlag { get; set; }
        public bool PF_Revaluation { get; set; }
        public int PF_AccType { get; set; }
        public bool PF_NeverOvrdDefPerfMthd { get; set; }
        public Nullable<int> Pf_GridViewPackage { get; set; }
        public bool PF_DORMANT { get; set; }
        public Nullable<int> PF_DORMANTUSER { get; set; }
        public Nullable<System.DateTime> PF_DORMANTDATE { get; set; }
        public Nullable<int> PF_ALTINVESTPROFILE { get; set; }
        public Nullable<int> PF_FREELIST1 { get; set; }
        public Nullable<int> PF_FREELIST2 { get; set; }
        public string PF_FREETEXT1 { get; set; }
        public string PF_FREETEXT2 { get; set; }
        public string PF_FREETEXT3 { get; set; }
        public string PF_FREETEXT4 { get; set; }
        public string PF_FREETEXT5 { get; set; }
        public string PF_FREETEXT6 { get; set; }
        public Nullable<decimal> PF_FREENUMBER1 { get; set; }
        public Nullable<decimal> PF_FREENUMBER2 { get; set; }
        public Nullable<decimal> PF_FREENUMBER3 { get; set; }
        public Nullable<System.DateTime> PF_FREEDATE1 { get; set; }
        public Nullable<System.DateTime> PF_FREEDATE2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
