//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_ADDRESS_TYPE
    {
        public int PAT_ID { get; set; }
        public string PAT_NAME1 { get; set; }
        public string PAT_NAME2 { get; set; }
    }
}
