//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public string PR_LINK { get; set; }
        public System.DateTime PR_DATE { get; set; }
        public Nullable<double> PR_OPEN { get; set; }
        public Nullable<double> PR_CLOSE { get; set; }
        public Nullable<double> PR_HI { get; set; }
        public Nullable<double> PR_LOW { get; set; }
        public Nullable<double> PR_VOLUME { get; set; }
        public Nullable<double> PR_HI_IRR { get; set; }
        public Nullable<double> PR_LOW_IRR { get; set; }
        public Nullable<double> PR_CLOSE_IRR { get; set; }
        public double PR_FACTOR { get; set; }
        public short PR_UNDERSUPERV { get; set; }
        public Nullable<double> PR_ADJ_PRICE { get; set; }
        public Nullable<double> PR_BID { get; set; }
        public Nullable<double> PR_ASK { get; set; }
        public Nullable<int> PR_Term { get; set; }
        public Nullable<int> PR_NumOfTerms { get; set; }
        public decimal PR_idx_Ratio { get; set; }
    }
}
