//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rates
    {
        public string RT_Object { get; set; }
        public int RT_Code { get; set; }
        public System.DateTime RT_Date { get; set; }
        public double RT_Amount { get; set; }
        public decimal RT_Percentage { get; set; }
        public decimal RT_SinkFactorPerc { get; set; }
        public decimal RT_DebitPercentage { get; set; }
        public Nullable<System.DateTime> RT_EndDate { get; set; }
        public Nullable<System.DateTime> RT_PmtDate { get; set; }
        public Nullable<int> RT_PeriodNo { get; set; }
        public Nullable<System.DateTime> RT_ActualPmntDate { get; set; }
        public Nullable<decimal> RT_TaxPerc { get; set; }
        public Nullable<decimal> RT_DaysNominator { get; set; }
        public Nullable<decimal> RT_EndAccrualsAmnt { get; set; }
        public Nullable<decimal> RT_EndTaxAmnt { get; set; }
        public decimal RT_CouponFactorPrc { get; set; }
        public Nullable<int> RT_DaysDenominator { get; set; }
        public Nullable<bool> RT_PDC { get; set; }
        public string RT_DocNo { get; set; }
    }
}
