//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titles()
        {
            this.Currencies = new HashSet<Currencies>();
            this.Currencies1 = new HashSet<Currencies>();
            this.Currencies2 = new HashSet<Currencies>();
        }
    
        public int T_Code { get; set; }
        public Nullable<int> T_Group { get; set; }
        public Nullable<short> T_Type { get; set; }
        public Nullable<int> T_Master { get; set; }
        public string T_Name1 { get; set; }
        public string T_Name2 { get; set; }
        public string T_ShortCut1 { get; set; }
        public string T_ShortCut2 { get; set; }
        public string T_Link1 { get; set; }
        public string T_Link2 { get; set; }
        public string T_Link3 { get; set; }
        public string T_Link4 { get; set; }
        public string T_FreeField1 { get; set; }
        public string T_FreeField2 { get; set; }
        public string T_FreeField3 { get; set; }
        public string T_FreeField4 { get; set; }
        public int T_Currency { get; set; }
        public Nullable<float> T_Tax { get; set; }
        public string T_Comment { get; set; }
        public Nullable<float> T_Beta { get; set; }
        public Nullable<System.DateTime> T_BetaDate { get; set; }
        public string T_ASCIIsymbol { get; set; }
        public Nullable<short> T_ViewInLists { get; set; }
        public Nullable<System.DateTime> T_InitDate { get; set; }
        public Nullable<System.DateTime> T_ExpDate { get; set; }
        public Nullable<short> T_Period { get; set; }
        public Nullable<short> T_Tokens { get; set; }
        public Nullable<int> T_BCurrency { get; set; }
        public Nullable<double> T_FaceValue { get; set; }
        public Nullable<float> T_Base { get; set; }
        public Nullable<short> T_Flag { get; set; }
        public Nullable<short> T_InASE { get; set; }
        public Nullable<short> T_ReCapitalize { get; set; }
        public Nullable<short> T_AverageCost { get; set; }
        public Nullable<double> T_Amount { get; set; }
        public string T_TSymbol { get; set; }
        public Nullable<double> T_FM0 { get; set; }
        public Nullable<double> T_FM1 { get; set; }
        public Nullable<double> T_FM2 { get; set; }
        public Nullable<double> T_FM3 { get; set; }
        public Nullable<double> T_FM4 { get; set; }
        public Nullable<double> T_FM5 { get; set; }
        public Nullable<double> T_FM6 { get; set; }
        public Nullable<double> T_FM7 { get; set; }
        public Nullable<double> T_FM8 { get; set; }
        public Nullable<double> T_FM9 { get; set; }
        public Nullable<float> T_Premium { get; set; }
        public Nullable<int> T_PFolio { get; set; }
        public Nullable<short> T_MONTH30 { get; set; }
        public string T_LinkExport1 { get; set; }
        public string T_LinkExport2 { get; set; }
        public string T_Link5 { get; set; }
        public int T_Market { get; set; }
        public Nullable<int> T_SubMarket { get; set; }
        public string T_ISIN { get; set; }
        public Nullable<short> T_XAAType { get; set; }
        public Nullable<short> T_BondType { get; set; }
        public Nullable<int> T_RelateRate { get; set; }
        public Nullable<int> T_Guarantor { get; set; }
        public Nullable<short> T_CalcType { get; set; }
        public Nullable<short> T_CalcTax { get; set; }
        public Nullable<System.DateTime> T_CouponDate { get; set; }
        public Nullable<int> T_NumOfWarningDates { get; set; }
        public Nullable<double> T_MaxQuantity { get; set; }
        public Nullable<int> T_PUCODE { get; set; }
        public Nullable<double> T_MinDenomination { get; set; }
        public Nullable<int> T_Secondary { get; set; }
        public double T_Factor { get; set; }
        public Nullable<int> T_OptionType { get; set; }
        public Nullable<short> T_DOAdd { get; set; }
        public Nullable<short> T_DOAddEOM { get; set; }
        public Nullable<short> T_DOAcc { get; set; }
        public Nullable<short> T_DOAccEOM { get; set; }
        public Nullable<short> T_AbNormalCoupon { get; set; }
        public int T_SubType { get; set; }
        public short T_AccType { get; set; }
        public int T_BOGExcemption { get; set; }
        public int T_ApproveIn { get; set; }
        public Nullable<int> T_SettleDays { get; set; }
        public int T_AccKind { get; set; }
        public string T_BuyCommScript { get; set; }
        public string T_SellCommScript { get; set; }
        public Nullable<int> T_SPRating { get; set; }
        public int T_Benchmark { get; set; }
        public Nullable<System.DateTime> T_IssueDate { get; set; }
        public Nullable<System.DateTime> T_CloseDate { get; set; }
        public Nullable<System.DateTime> T_DeactiveDate { get; set; }
        public int T_SettlePlace { get; set; }
        public int T_DefBroker { get; set; }
        public int T_TSDefBroker { get; set; }
        public int T_CSDefBroker { get; set; }
        public int T_TSDEFBrokerAgent { get; set; }
        public string T_SafeAccountOnAgent { get; set; }
        public string T_AgentCode { get; set; }
        public string T_TSDefBrokerCode { get; set; }
        public Nullable<int> T_MarketSector { get; set; }
        public Nullable<int> T_Moodys { get; set; }
        public string T_CUSIP { get; set; }
        public string T_CollType { get; set; }
        public string T_IssueType { get; set; }
        public Nullable<decimal> T_IssuedFV { get; set; }
        public Nullable<decimal> T_OutstdFV { get; set; }
        public Nullable<short> T_CouponType { get; set; }
        public int T_YieldType { get; set; }
        public Nullable<int> T_TRADEPRICETYPE { get; set; }
        public Nullable<int> T_PRCID { get; set; }
        public int T_Scenarios { get; set; }
        public Nullable<int> T_TaxOnFV { get; set; }
        public Nullable<int> T_TaxPolicy { get; set; }
        public Nullable<int> T_SettleDaysBuy { get; set; }
        public Nullable<byte> T_PeriodType { get; set; }
        public Nullable<System.DateTime> T_InsertDate { get; set; }
        public byte T_IsTemplate { get; set; }
        public Nullable<int> T_RiskLevelGroup { get; set; }
        public Nullable<byte> T_MifidRel { get; set; }
        public Nullable<byte> T_MifidType { get; set; }
        public double T_MinTradeVolume { get; set; }
        public Nullable<int> T_RelateRateDaysOffset { get; set; }
        public string T_SEDOL { get; set; }
        public Nullable<int> T_IssuerCountry { get; set; }
        public bool T_CouponsEOM { get; set; }
        public Nullable<int> T_INDUSTRYSECTORS { get; set; }
        public Nullable<int> T_INDUSTRYGROUPS { get; set; }
        public Nullable<int> T_INDUSTRIES { get; set; }
        public Nullable<int> T_INDUSTRYSUBS { get; set; }
        public bool T_MarginAcc { get; set; }
        public int T_CapAdjOpt { get; set; }
        public bool T_HasDisclaimer { get; set; }
        public string T_Disclaimer { get; set; }
        public int T_RedemptionOption { get; set; }
        public bool T_Sinkable { get; set; }
        public bool T_InflationLinked { get; set; }
        public Nullable<int> T_InflationLinkedType { get; set; }
        public int T_Tier { get; set; }
        public decimal T_PaybackFactorPrc { get; set; }
        public bool T_UseCustomDCC { get; set; }
        public bool T_CapitalGuaranteed { get; set; }
        public decimal T_MinCapitalGuaranteedPrc { get; set; }
        public bool T_CouponGuaranteed { get; set; }
        public Nullable<int> T_FitchRating { get; set; }
        public Nullable<int> T_QntDecimals { get; set; }
        public Nullable<int> T_PrcDecimals { get; set; }
        public Nullable<int> T_EncapsulationOpt { get; set; }
        public Nullable<int> T_EvalMethod { get; set; }
        public bool T_Convertible { get; set; }
        public int T_RnwOption { get; set; }
        public int T_PmntOption { get; set; }
        public int T_ExerciseAmntOpt { get; set; }
        public Nullable<decimal> T_StrikePrice { get; set; }
        public int T_ValMethod { get; set; }
        public int T_ValType { get; set; }
        public Nullable<decimal> T_MngmntFeePrc { get; set; }
        public Nullable<decimal> T_InsrncFeePrc { get; set; }
        public bool T_HoldSaleOrder { get; set; }
        public bool T_CMNSTOCKFLAG { get; set; }
        public bool T_HoldPurcOrder { get; set; }
        public bool T_PerpetualFlag { get; set; }
        public bool T_SeniorFlag { get; set; }
        public bool T_CoveredFlag { get; set; }
        public bool T_SubscriptionPeriodFlag { get; set; }
        public bool T_PledgeFlag { get; set; }
        public Nullable<decimal> T_SubscrAmnt { get; set; }
        public Nullable<int> T_SubscrCustNum { get; set; }
        public Nullable<int> T_SPOutlook { get; set; }
        public Nullable<int> T_MoodysOutlook { get; set; }
        public Nullable<int> T_FitchOutlook { get; set; }
        public Nullable<byte> T_BLOOMBERGTYPE { get; set; }
        public Nullable<int> T_TradingCRDCode { get; set; }
        public Nullable<int> T_ExtFeedModelId { get; set; }
        public Nullable<int> T_BondCalcTerms { get; set; }
        public Nullable<int> T_MarketXOFF { get; set; }
        public int T_InitSource { get; set; }
        public Nullable<byte> T_BBGPRCSOURCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies2 { get; set; }
    }
}
