//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitleCategory
    {
        public int TC_Code { get; set; }
        public string TC_Name { get; set; }
        public string TC_Name2 { get; set; }
        public Nullable<int> TC_NUMBER1 { get; set; }
        public string TC_TEXT1 { get; set; }
        public bool TC_ShariaRelated { get; set; }
        public Nullable<byte> TC_BBGPRCSOURCE { get; set; }
    }
}
